# Generated by Django 3.2.8 on 2021-11-21 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_helpmework_imgsrcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmework',
            name='imgsrcs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='', size=None),
        ),
    ]
