# Generated by Django 3.2.8 on 2021-11-23 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_helpmework_imgsrcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmework',
            name='imgsrcs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default='no img', size=None),
        ),
        migrations.AlterField(
            model_name='helpmework',
            name='subject',
            field=models.CharField(default='not specified', max_length=20),
        ),
    ]
