# Generated by Django 3.2.8 on 2021-11-23 11:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211123_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmework',
            name='imgsrcs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=['no_img'], size=None),
        ),
    ]
