# Generated by Django 3.2.8 on 2021-12-04 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mainprofile_pending_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='pending_works',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
