# Generated by Django 3.2.8 on 2021-12-05 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmework',
            name='workdone_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
